export const buttonOpen = document.querySelector('#buttonOpen');
export const modalFilter = document.querySelector('#modalFilter');
export const modalClose = document.querySelector('#modalFilter  .modalClose');
export const overlay = document.querySelector('#modalFilter .overlay');
export const friendsList1 = document.querySelector('#friendsList1');
export const friendsList2 = document.querySelector('#friendsList2');
export const filterInput1 = document.querySelector('#filterInput1');
export const filterInput2 = document.querySelector('#filterInput2');
export const saveListsBtn = document.querySelector('#saveListsBtn');
